- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: add Kubernetes' YUM repository
      yum_repository:
        name: Kubernetes
        description: Kubernetes YUM repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes
      tags:
        - kube

    - name: install kubectl
      yum:
          name: kubectl
          state: present
          update_cache: true
      tags:
        - kube

    - name: install kubelet
      yum:
          name: kubelet
          state: present
          update_cache: true
      tags:
        - kube

    - name: install kubeadm
      yum:
          name: kubeadm
          state: present
      tags:
        - kube

    - name: start kubelet
      service:
        name: kubelet
        enabled: yes
        state: started
      tags:
        - kube

