apiVersion: v1
kind: Service
metadata:
  name: mvcapp
spec:
  type: NodePort
  #type: LoadBalancer
  #loadBalancerIP: 192.168.0.10
  selector:
    app: mvcapp
  ports:
  - port: 80
    targetPort: 80

